import re
from typing import List, Tuple, Union

class GroundingValidator:
    """
    Validates that LLM explanations for chess moves are grounded in the provided Engine PV data.
    Ensures that the LLM does not hallucinate moves or variations not present in the engine's calculation.
    """

    def __init__(self):
        # Regular expressions to match typical standard algebraic notation (SAN) and UCI moves
        # This regex is simplified and might need refinement for edge cases, but covers standard outputs.
        self.san_regex = re.compile(r'\b([KQRBN]?[a-h]?[1-8]?x?[a-h][1-8](?:=[QRBN])?[+#]?|O-O(?:-O)?)\b')
        self.uci_regex = re.compile(r'\b([a-h][1-8][a-h][1-8][qrbn]?)\b')
        
        # False positives to ignore (single letters or common words that might match loosely)
        self.ignore_list = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'O', 'x', 'K', 'Q', 'R', 'B', 'N'}

    def extract_moves(self, text: str) -> set:
        """Extracts chess moves from a block of text."""
        moves = set()
        
        for match in self.san_regex.finditer(text):
            moves.add(match.group(1))
            
        for match in self.uci_regex.finditer(text):
            moves.add(match.group(1))
            
        return {m for m in moves if m not in self.ignore_list}

    def validate(self, llm_response: str, pv_data: Union[str, List[str]]) -> Tuple[bool, str]:
        """
        Validates the LLM response against the PV data.
        
        Args:
            llm_response: The text explanation generated by the LLM.
            pv_data: A list of moves in the PV, or a string representing the PV line.
            
        Returns:
            A tuple containing a boolean (True if valid, False otherwise) and a feedback string.
        """
        mentioned_moves = self.extract_moves(llm_response)
        
        # Parse PV data into a set of valid moves
        if isinstance(pv_data, str):
            valid_moves = self.extract_moves(pv_data)
        else:
            # Assuming it's an iterable of moves
            valid_moves = set()
            for item in pv_data:
                valid_moves.update(self.extract_moves(str(item)))
                
        # Find moves mentioned in the response that are NOT in the PV data
        ungrounded_moves = mentioned_moves - valid_moves
        
        if ungrounded_moves:
            feedback = (
                f"Validation Failed: Your explanation mentioned moves not found in the PV data: "
                f"{', '.join(sorted(ungrounded_moves))}. "
                f"Please restrict your analysis to the provided lines only."
            )
            return False, feedback
            
        return True, "Validation Passed: Explanation is grounded in the PV data."
